import { useState } from 'react'

const projects = [
  { name: 'Choco Vault', type: 'Full-Stack E-Commerce Platform', description: 'A production e-commerce platform for a coffee and chocolate business, developed and deployed for a paying client.', stack: ['React', 'Node.js', 'Express', 'MySQL', 'JWT', 'Razorpay'], featured: true, details: [['Product experience', 'Responsive React and Vite frontend with Tailwind CSS, React Router, Axios, Zustand, and protected user and admin routes.'], ['Platform', 'REST APIs with Express, MySQL data management, JWT authentication, bcrypt password hashing, and Google OAuth 2.0 login.'], ['Reliability', 'Backend validation, API rate limiting, indexed MySQL columns for efficient queries, and Razorpay in test mode for checkout development.'], ['Delivery', 'Configured basic GitHub Actions CI and deployed across Render, Cloudflare Pages, TiDB Cloud, and Cloudflare DNS.']] },
  { name: 'Team Task System', type: 'Full-Stack Workflow Application', description: 'A team task and issue-management platform for projects, assignments, and collaboration workflows.', stack: ['React', 'Node.js', 'Express', 'MySQL', 'JWT', 'REST APIs'], details: [['Workflow', 'Supports project tracking, task CRUD operations, assignments, and comment threads through RESTful APIs.'], ['Access control', 'Uses JWT-based role-based access control to distinguish admin and employee workflows.'], ['Dashboard', 'Provides responsive task status tracking, dynamic filtering, search, and project-management interfaces.']] },
  { name: 'Sports Analyzer', type: 'AI-Powered Gameplay Analysis', description: 'A computer-vision application that extracts useful insights from badminton footage rather than simply playing video.', stack: ['Python', 'OpenCV', 'YOLO', 'Streamlit', 'NumPy', 'Pandas'], details: [['Computer vision', 'Uses YOLO/Ultralytics-based detection to identify players and gameplay elements in video footage.'], ['Analysis', 'Processes visual data with NumPy, Pandas, SciPy, and Matplotlib to support meaningful sports analysis.'], ['Interface', 'Presents the workflow through an interactive Streamlit application.']] },
  { name: 'AI Image Studio', type: 'Computer Vision Application', description: 'An interactive image-processing studio exploring enhancement, colorization, segmentation, and depth estimation.', stack: ['Python', 'OpenCV', 'Streamlit', 'Computer Vision'], details: [['Image workflow', 'Brings multiple computer-vision capabilities together in one approachable interactive interface.'], ['Focus', 'Explores practical image enhancement and analysis workflows with Python and OpenCV.']] },
  { name: 'DSA Visualizer', type: 'Interactive Learning Concept', description: 'A visual approach to understanding data structures and algorithms through step-by-step animated execution.', stack: ['JavaScript', 'Algorithms', 'Data Structures'], details: [['Learning goal', 'Designed to make algorithm behaviour easier to understand before diving into implementation details.'], ['Concept', 'Intended to explore visual, interactive representations of data structures and algorithm operations.']] },
]

function ProjectCard({ project }) {
  const [isExpanded, setIsExpanded] = useState(false)
  return <article className={`project-card ${project.featured ? 'project-card--featured' : ''}`}><div className="project-card__header"><p>{project.type}</p>{project.featured && <span>FEATURED</span>}</div><h3>{project.name}</h3><p className="project-card__description">{project.description}</p><ul className="project-card__stack" aria-label={`${project.name} technologies`}>{project.stack.map((item) => <li key={item}>{item}</li>)}</ul><button className="project-card__toggle" type="button" aria-expanded={isExpanded} onClick={() => setIsExpanded((expanded) => !expanded)}>{isExpanded ? 'Close details' : 'Project details'} <span aria-hidden="true">{isExpanded ? '↑' : '↓'}</span></button>{isExpanded && <div className="project-card__details">{project.details.map(([heading, text]) => <div key={heading}><h4>{heading}</h4><p>{text}</p></div>)}</div>}</article>
}

function Projects() { return <section className="projects" id="projects" aria-labelledby="projects-title"><div className="projects__inner"><div className="section-frame__top"><span className="section-frame__number">(02)</span><p className="section-frame__label">Projects in focus</p></div><h2 id="projects-title">Selected work</h2><div className="projects__grid">{projects.map((project) => <ProjectCard key={project.name} project={project} />)}</div></div></section> }
export default Projects
